Update nixpkgs and pin home-manager
home-manager is failing in the devbox as it is using a feature that is not yet in our
version of nixpkgs:

```
$ home-manager switch
trace: warning: The option `programs.direnv.enableNixDirenvIntegration' defined in `/vagrant/home/modules/profiles/zsh.nix' and `/home/vagrant/.config/nixpkgs/modules/profiles/direnv.nix' has been renamed to `programs.direnv.nix-direnv.enable'.
error: anonymous function at /nix/store/39sygnjdxwzj5g0kkbwnz6rfh0rj66fn-nixpkgs/nixpkgs/pkgs/tools/misc/nix-direnv/default.nix:1:1 called with unexpected argument 'enableFlakes', at /nix/store/39sygnjdxwzj5g0kkbwnz6rfh0rj66fn-nixpkgs/nixpkgs/lib/customisation.nix:69:16
```

Indeed the option has been added here in nixpkgs: https://github.com/NixOS/nixpkgs/pull/126176/

We update nixpkgs to latest released version of 21.05
(https://github.com/NixOS/nixpkgs/commit/93963c27b934f24289a94b9e3784d60a9b77e92c).

We pin home-manager to the current HEAD of the `release-21.05` branch
(https://github.com/nix-community/home-manager/commit/35a24648d155843a4d162de98c17b1afd5db51e4).